name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
      
      - name: Install osrm-backend dependencies
        run: |
          sudo apt install libtbb-dev
          sudo apt install liblua5.2-dev
          sudo apt install libboost1.74-all-dev

      - name: Install py-osrm and doc dependencies
        run: |
          pip install .
          pip install -r docs/requirements.txt

      - name: Build and deploy to GitHub Pages
        working-directory: docs
        run: |
          mkdocs gh-deploy --force
