name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      # Install osrm-backend
      - name: Checkout osrm-backend
        uses: actions/checkout@v3
        with:
          repository: Project-OSRM/osrm-backend
          ref: db7946d76246cb10a5710c8f2851997417940b55
          submodules: true
          fetch-depth: 1
          path: osrm-backend
      
      - name: Build osrm-backend
        working-directory: osrm-backend
        run: |
          sudo apt install libtbb-dev
          sudo apt install liblua5.2-dev
          sudo apt install libboost1.74-all-dev
          
          mkdir build && cd build &&
          cmake ..
          make -j$(nproc)
          sudo make install
      # ====================

      - name: Install dependencies
        run: |
          pip install .
          pip install -r docs/requirements.txt
 
      - name: Build and deploy to GitHub Pages
        working-directory: docs
        run: |
          mkdocs gh-deploy --force
