name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build_wheels:
    name: PR - cp*, ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}-${{ matrix.version }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu]
        version: [latest]

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Run CIBuildWheel
      uses: pypa/cibuildwheel@v2.14.1
