name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build_wheels:
    name: PR - cp38*, ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}-${{ matrix.version }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu, macos]
        version: [latest]
    env:
      GITHUB_TOKEN: ${{ github.token }}
      ARTIFACT_WORKFLOW: osrm-backend.yml

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Get osrm-backend Artifact ID
      if: matrix.platform != 'ubuntu'
      run: |
        echo ARTIFACT_ID=$( \
          gh api -X GET \
          repos/${{ github.repository }}/actions/workflows/${{ env.ARTIFACT_WORKFLOW }}/runs \
          --field status='success' \
          --field per_page=1 \
          | jq '.["workflow_runs"][0].id') \
        >> $GITHUB_ENV

    - name: Run CIBuildWheel
      uses: pypa/cibuildwheel@v2.14.1
      env:
        CIBW_BUILD: cp38*

        CIBW_BEFORE_ALL_MACOS: |
          gh run download ${{ env.ARTIFACT_ID }} -n osrm-backend_${{ matrix.platform }}
